name: 'Buildy Uploader'
description: 'Uploads builds to the Buildy S3 Bucket'
inputs:
  build-directory:
    required: true
    description: 'Path to the directory to be uploaded'
runs:
  using: "composite"
  steps:

    #Branch name from GITHUB_REF or ${{ github.head_ref }} include refs/heads/$BranchName This step cleans up the refs/heads/
    - name: Extract branch name
      shell: bash
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
      id: extract_branch

    #Buildy uses IOS instead of iOS, this setps capitalizes iOS to IOS
    - name: Capitalize Target
      shell: pwsh
      id: capitalize
      run: |
        $result = $env:TARGET.substring(0,1).toupper()+$env:TARGET.substring(1)
        echo "::set-output name=target::$result"
      
    - name: Upload Build to S3
      shell: bash
      run: |
        aws s3 cp ${{ inputs.build-directory }} s3://$BUILDY_BUCKET/$BUILDY_DIRECTORY --metadata "$METADATA" --recursive --exclude "*.zip"
      env:
        METADATA: ${{ format('{{"GitBranch":"{0}", "GitCommit":"{1}", "GitUrl":"{2}"}}', steps.extract_branch.outputs.branch, github.sha, github.repository) }}
        BUILDY_DIRECTORY: ${{env.BUILD_NAME}}/${{steps.capitalize.outputs.target}}/${{env.STABILITY}}
      
      # Sync Buildy Directory Metafile
    - name: Create S3 Meta Directory
      shell: bash
      run: |
        mkdir meta
        touch meta/$BUILD_NAME.$TARGET.$STABILITY
        aws s3 sync meta/. s3://$BUILDY_BUCKET/$BUILDY_META_DIRECTORY
      env:
        BUILDY_META_DIRECTORY: '.buildy-web-metadata'
